export const jobDatas = [
  {
      id:1,
      postedOn : '2024-09-01',
      title: 'Android Developer',
      company: 'Apple',
      type: 'Full Time',
      experience: 'Mid Level',
      location: 'Remote',
      skills: ["Bitbucket", "React Native", "Kotlin"],
      job_link: "https://www.apple.com/careers/in/",
  },
  {
      id: 2,
      postedOn: '2024-09-01',
      title: "Frontend Developer",
      type: "Full time",
      location: "In-office",
      experience: "Fresher",
      company: "Amazon",
      skills: ["Javascript", "Nextjs", "Tailwind CSS"],
      job_link: "https://www.amazon.jobs/en/",
    },
    {
      id: 3,
      postedOn: '2024-08-31',
      title: "Backend Developer",
      type: "Part time",
      location: "Remote",
      experience: "Senior Level",
      company: "Facebook",
      skills: ["Kotlin", "MVVM"],
      job_link: "https://facebook.com/careers",
    },
    {
      id: 4,
      postedOn: '2024-09-02',
      title: "FullStack Developer",
      type: "Contract",
      location: "Hybrid",
      experience: "Junior Level",
      company: "Netflix",
      companyUrl: "https://facebook.com",
      skills: ["web3", "Content Creation", "Community"],
      job_link: "https://jobs.netflix.com/",
    },
]